//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var color: color { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }

  func color(bundle: Foundation.Bundle) -> color {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func validate() throws {

  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.color` struct is generated, and contains static references to 20 colors.
  struct color {
    let bundle: Foundation.Bundle

    /// Color `AccentBlack`.
    var accentBlack: RswiftResources.ColorResource { .init(name: "AccentBlack", path: [], bundle: bundle) }

    /// Color `AccentBlackSecondary`.
    var accentBlackSecondary: RswiftResources.ColorResource { .init(name: "AccentBlackSecondary", path: [], bundle: bundle) }

    /// Color `AccentBlue`.
    var accentBlue: RswiftResources.ColorResource { .init(name: "AccentBlue", path: [], bundle: bundle) }

    /// Color `AccentBrown`.
    var accentBrown: RswiftResources.ColorResource { .init(name: "AccentBrown", path: [], bundle: bundle) }

    /// Color `AccentColor`.
    var accentColor: RswiftResources.ColorResource { .init(name: "AccentColor", path: [], bundle: bundle) }

    /// Color `AccentGreen`.
    var accentGreen: RswiftResources.ColorResource { .init(name: "AccentGreen", path: [], bundle: bundle) }

    /// Color `AccentRed`.
    var accentRed: RswiftResources.ColorResource { .init(name: "AccentRed", path: [], bundle: bundle) }

    /// Color `BackgroundBase`.
    var backgroundBase: RswiftResources.ColorResource { .init(name: "BackgroundBase", path: [], bundle: bundle) }

    /// Color `BackgroundSecondary`.
    var backgroundSecondary: RswiftResources.ColorResource { .init(name: "BackgroundSecondary", path: [], bundle: bundle) }

    /// Color `BackgroundTertiary`.
    var backgroundTertiary: RswiftResources.ColorResource { .init(name: "BackgroundTertiary", path: [], bundle: bundle) }

    /// Color `IconBase`.
    var iconBase: RswiftResources.ColorResource { .init(name: "IconBase", path: [], bundle: bundle) }

    /// Color `IconSecondary`.
    var iconSecondary: RswiftResources.ColorResource { .init(name: "IconSecondary", path: [], bundle: bundle) }

    /// Color `IconWhite`.
    var iconWhite: RswiftResources.ColorResource { .init(name: "IconWhite", path: [], bundle: bundle) }

    /// Color `LineBase`.
    var lineBase: RswiftResources.ColorResource { .init(name: "LineBase", path: [], bundle: bundle) }

    /// Color `LineSecondary`.
    var lineSecondary: RswiftResources.ColorResource { .init(name: "LineSecondary", path: [], bundle: bundle) }

    /// Color `LineTertiary`.
    var lineTertiary: RswiftResources.ColorResource { .init(name: "LineTertiary", path: [], bundle: bundle) }

    /// Color `LineWhite`.
    var lineWhite: RswiftResources.ColorResource { .init(name: "LineWhite", path: [], bundle: bundle) }

    /// Color `TextBase`.
    var textBase: RswiftResources.ColorResource { .init(name: "TextBase", path: [], bundle: bundle) }

    /// Color `TextSecondary`.
    var textSecondary: RswiftResources.ColorResource { .init(name: "TextSecondary", path: [], bundle: bundle) }

    /// Color `TextWhite`.
    var textWhite: RswiftResources.ColorResource { .init(name: "TextWhite", path: [], bundle: bundle) }
  }

  /// This `_R.image` struct is generated, and contains static references to 97 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `BaristaFavorites`.
    var baristaFavorites: RswiftResources.ImageResource { .init(name: "BaristaFavorites", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Basil Lemon Sherbet Blended`.
    var basilLemonSherbetBlended: RswiftResources.ImageResource { .init(name: "Basil Lemon Sherbet Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Black Tea Lemonade Starbucks Fizziom`.
    var blackTeaLemonadeStarbucksFizziom: RswiftResources.ImageResource { .init(name: "Black Tea Lemonade Starbucks Fizziom", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Caramel Frappuccino`.
    var caramelFrappuccino: RswiftResources.ImageResource { .init(name: "Caramel Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `CartisKulig`.
    var cartisKulig: RswiftResources.ImageResource { .init(name: "CartisKulig", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Chocolate Affogato`.
    var chocolateAffogato: RswiftResources.ImageResource { .init(name: "Chocolate Affogato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Chocolate Cream Chip Frappuccino`.
    var chocolateCreamChipFrappuccino: RswiftResources.ImageResource { .init(name: "Chocolate Cream Chip Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `CoffeeStarbucks Double Shot`.
    var coffeeStarbucksDoubleShot: RswiftResources.ImageResource { .init(name: "CoffeeStarbucks Double Shot", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Cold Brew`.
    var coldBrew: RswiftResources.ImageResource { .init(name: "Cold Brew", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Cold Brew with Oat`.
    var coldBrewWithOat: RswiftResources.ImageResource { .init(name: "Cold Brew with Oat", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Cool Lime Starbucks Fizziom`.
    var coolLimeStarbucksFizziom: RswiftResources.ImageResource { .init(name: "Cool Lime Starbucks Fizziom", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Dolce Cold Brew`.
    var dolceColdBrew: RswiftResources.ImageResource { .init(name: "Dolce Cold Brew", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Double Espresso Chip Frappuccino`.
    var doubleEspressoChipFrappuccino: RswiftResources.ImageResource { .init(name: "Double Espresso Chip Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Espresso`.
    var espresso: RswiftResources.ImageResource { .init(name: "Espresso", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Espresso Con Panna`.
    var espressoConPanna: RswiftResources.ImageResource { .init(name: "Espresso Con Panna", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Espresso Macchiato`.
    var espressoMacchiato: RswiftResources.ImageResource { .init(name: "Espresso Macchiato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `FindYourTaste`.
    var findYourTaste: RswiftResources.ImageResource { .init(name: "FindYourTaste", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Hazelnut Starbucks Double Shot`.
    var hazelnutStarbucksDoubleShot: RswiftResources.ImageResource { .init(name: "Hazelnut Starbucks Double Shot", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `HyundaiCard`.
    var hyundaiCard: RswiftResources.ImageResource { .init(name: "HyundaiCard", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Blonde Caffe Americano`.
    var icedBlondeCaffeAmericano: RswiftResources.ImageResource { .init(name: "Iced Blonde Caffe Americano", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Blonde Caffe Latte`.
    var icedBlondeCaffeLatte: RswiftResources.ImageResource { .init(name: "Iced Blonde Caffe Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Blonde Starbucks Dolce Latte`.
    var icedBlondeStarbucksDolceLatte: RswiftResources.ImageResource { .init(name: "Iced Blonde Starbucks Dolce Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Blonde Vanilla Double Shot Macchiato`.
    var icedBlondeVanillaDoubleShotMacchiato: RswiftResources.ImageResource { .init(name: "Iced Blonde Vanilla Double Shot Macchiato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Brown Sugar Oat Shaken Espresso`.
    var icedBrownSugarOatShakenEspresso: RswiftResources.ImageResource { .init(name: "Iced Brown Sugar Oat Shaken Espresso", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Caffe Americano`.
    var icedCaffeAmericano: RswiftResources.ImageResource { .init(name: "Iced Caffe Americano", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Caffe Latte`.
    var icedCaffeLatte: RswiftResources.ImageResource { .init(name: "Iced Caffe Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Caffe Mocha`.
    var icedCaffeMocha: RswiftResources.ImageResource { .init(name: "Iced Caffe Mocha", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Cappuccino`.
    var icedCappuccino: RswiftResources.ImageResource { .init(name: "Iced Cappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Caramel Macchiato`.
    var icedCaramelMacchiato: RswiftResources.ImageResource { .init(name: "Iced Caramel Macchiato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Choux Cream Latte`.
    var icedChouxCreamLatte: RswiftResources.ImageResource { .init(name: "Iced Choux Cream Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced DECAF Caffe Americano`.
    var icedDECAFCaffeAmericano: RswiftResources.ImageResource { .init(name: "Iced DECAF Caffe Americano", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced DECAF Caffe Latte`.
    var icedDECAFCaffeLatte: RswiftResources.ImageResource { .init(name: "Iced DECAF Caffe Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced DECAF Caramel Macchiato`.
    var icedDECAFCaramelMacchiato: RswiftResources.ImageResource { .init(name: "Iced DECAF Caramel Macchiato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Earl Grey Vanilla Tea Latte`.
    var icedEarlGreyVanillaTeaLatte: RswiftResources.ImageResource { .init(name: "Iced Earl Grey Vanilla Tea Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Half DECAF Caffe Americano`.
    var icedHalfDECAFCaffeAmericano: RswiftResources.ImageResource { .init(name: "Iced Half DECAF Caffe Americano", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Half DECAF Caffe Latte`.
    var icedHalfDECAFCaffeLatte: RswiftResources.ImageResource { .init(name: "Iced Half DECAF Caffe Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Half DECAF Caramel Macchiato`.
    var icedHalfDECAFCaramelMacchiato: RswiftResources.ImageResource { .init(name: "Iced Half DECAF Caramel Macchiato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Half DECAF Starbucks Dolce Latte`.
    var icedHalfDECAFStarbucksDolceLatte: RswiftResources.ImageResource { .init(name: "Iced Half DECAF Starbucks Dolce Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Malcha Latte from Jeju Organic Farm`.
    var icedMalchaLatteFromJejuOrganicFarm: RswiftResources.ImageResource { .init(name: "Iced Malcha Latte from Jeju Organic Farm", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Signature Chocolate`.
    var icedSignatureChocolate: RswiftResources.ImageResource { .init(name: "Iced Signature Chocolate", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced Starbucks Dolce Latte`.
    var icedStarbucksDolceLatte: RswiftResources.ImageResource { .init(name: "Iced Starbucks Dolce Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced The Green Mugwort Cream Latte`.
    var icedTheGreenMugwortCreamLatte: RswiftResources.ImageResource { .init(name: "Iced The Green Mugwort Cream Latte", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Iced White Chocolate Mocha`.
    var icedWhiteChocolateMocha: RswiftResources.ImageResource { .init(name: "Iced White Chocolate Mocha", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Java Chip Chocolate Affogato`.
    var javaChipChocolateAffogato: RswiftResources.ImageResource { .init(name: "Java Chip Chocolate Affogato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Java Chip Frappuccino`.
    var javaChipFrappuccino: RswiftResources.ImageResource { .init(name: "Java Chip Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Java Chip Vanilla Affogato`.
    var javaChipVanillaAffogato: RswiftResources.ImageResource { .init(name: "Java Chip Vanilla Affogato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Jeiu Black Sesame Cream Frappuccino`.
    var jeiuBlackSesameCreamFrappuccino: RswiftResources.ImageResource { .init(name: "Jeiu Black Sesame Cream Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Jeju Citrus Honey Cold Brew`.
    var jejuCitrusHoneyColdBrew: RswiftResources.ImageResource { .init(name: "Jeju Citrus Honey Cold Brew", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Jeju Forest Cold Brew`.
    var jejuForestColdBrew: RswiftResources.ImageResource { .init(name: "Jeju Forest Cold Brew", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Jeju Golden Tangerine Blended`.
    var jejuGoldenTangerineBlended: RswiftResources.ImageResource { .init(name: "Jeju Golden Tangerine Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Jeju Malcha & Apple Mango Blended`.
    var jejuMalchaAppleMangoBlended: RswiftResources.ImageResource { .init(name: "Jeju Malcha & Apple Mango Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Jeju Mugwort Cream Frappuccino`.
    var jejuMugwortCreamFrappuccino: RswiftResources.ImageResource { .init(name: "Jeju Mugwort Cream Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `LoveUs`.
    var loveUs: RswiftResources.ImageResource { .init(name: "LoveUs", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Malcha Cream Frappuccino from Jeju Organic Farm`.
    var malchaCreamFrappuccinoFromJejuOrganicFarm: RswiftResources.ImageResource { .init(name: "Malcha Cream Frappuccino from Jeju Organic Farm", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Mango Banana Blended`.
    var mangoBananaBlended: RswiftResources.ImageResource { .init(name: "Mango Banana Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Mango Passion Tea Blended`.
    var mangoPassionTeaBlended: RswiftResources.ImageResource { .init(name: "Mango Passion Tea Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Milk`.
    var milk: RswiftResources.ImageResource { .init(name: "Milk", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Mint Chocolate Chip Blended`.
    var mintChocolateChipBlended: RswiftResources.ImageResource { .init(name: "Mint Chocolate Chip Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Nitro Cold Brew`.
    var nitroColdBrew: RswiftResources.ImageResource { .init(name: "Nitro Cold Brew", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Nitro Vanilla Cream`.
    var nitroVanillaCream: RswiftResources.ImageResource { .init(name: "Nitro Vanilla Cream", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Passion Tango Tea Lemonade Starbucks Fizziom`.
    var passionTangoTeaLemonadeStarbucksFizziom: RswiftResources.ImageResource { .init(name: "Passion Tango Tea Lemonade Starbucks Fizziom", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Pink Drink with Strawberry Acai Starbucks Refreshers`.
    var pinkDrinkWithStrawberryAcaiStarbucksRefreshers: RswiftResources.ImageResource { .init(name: "Pink Drink with Strawberry Acai Starbucks Refreshers", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Pink Flower Youthberry Tea`.
    var pinkFlowerYouthberryTea: RswiftResources.ImageResource { .init(name: "Pink Flower Youthberry Tea", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Red Power Passion Tea`.
    var redPowerPassionTea: RswiftResources.ImageResource { .init(name: "Red Power Passion Tea", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Red Power Smash Blended`.
    var redPowerSmashBlended: RswiftResources.ImageResource { .init(name: "Red Power Smash Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Signature The Black Cold Brew`.
    var signatureTheBlackColdBrew: RswiftResources.ImageResource { .init(name: "Signature The Black Cold Brew", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Spring Strawberry Milk`.
    var springStrawberryMilk: RswiftResources.ImageResource { .init(name: "Spring Strawberry Milk", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `StayChillStayPlayful`.
    var stayChillStayPlayful: RswiftResources.ImageResource { .init(name: "StayChillStayPlayful", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Steamed Milk`.
    var steamedMilk: RswiftResources.ImageResource { .init(name: "Steamed Milk", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Strawberry Acai with Lemonade Starbucks Refreshers`.
    var strawberryAcaiWithLemonadeStarbucksRefreshers: RswiftResources.ImageResource { .init(name: "Strawberry Acai with Lemonade Starbucks Refreshers", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Strawberry Delight Yogurt Blended`.
    var strawberryDelightYogurtBlended: RswiftResources.ImageResource { .init(name: "Strawberry Delight Yogurt Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `SummerBaeverage`.
    var summerBaeverage: RswiftResources.ImageResource { .init(name: "SummerBaeverage", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `The Green Mugwort Blended`.
    var theGreenMugwortBlended: RswiftResources.ImageResource { .init(name: "The Green Mugwort Blended", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Vanilla Aftogato`.
    var vanillaAftogato: RswiftResources.ImageResource { .init(name: "Vanilla Aftogato", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Vanilla Cream Cold Brew`.
    var vanillaCreamColdBrew: RswiftResources.ImageResource { .init(name: "Vanilla Cream Cold Brew", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Vanilla Cream Frappuccino`.
    var vanillaCreamFrappuccino: RswiftResources.ImageResource { .init(name: "Vanilla Cream Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Vanilla Flat White`.
    var vanillaFlatWhite: RswiftResources.ImageResource { .init(name: "Vanilla Flat White", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Vanilla Starbucks Double Shot`.
    var vanillaStarbucksDoubleShot: RswiftResources.ImageResource { .init(name: "Vanilla Starbucks Double Shot", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `White Chocolate Mocha Frappuccino`.
    var whiteChocolateMochaFrappuccino: RswiftResources.ImageResource { .init(name: "White Chocolate Mocha Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `White Tiger Frappuccino`.
    var whiteTigerFrappuccino: RswiftResources.ImageResource { .init(name: "White Tiger Frappuccino", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `Yuja Passion Starbucks Fizzio`.
    var yujaPassionStarbucksFizzio: RswiftResources.ImageResource { .init(name: "Yuja Passion Starbucks Fizzio", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `add.circle`.
    var addCircle: RswiftResources.ImageResource { .init(name: "add.circle", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `arrow.right`.
    var arrowRight: RswiftResources.ImageResource { .init(name: "arrow.right", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bascket`.
    var bascket: RswiftResources.ImageResource { .init(name: "bascket", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `chevron.left`.
    var chevronLeft: RswiftResources.ImageResource { .init(name: "chevron.left", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `heart`.
    var heart: RswiftResources.ImageResource { .init(name: "heart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `house`.
    var house: RswiftResources.ImageResource { .init(name: "house", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `logo`.
    var logo: RswiftResources.ImageResource { .init(name: "logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `magnifying.glass`.
    var magnifyingGlass: RswiftResources.ImageResource { .init(name: "magnifying.glass", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `marker`.
    var marker: RswiftResources.ImageResource { .init(name: "marker", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `minus.circle`.
    var minusCircle: RswiftResources.ImageResource { .init(name: "minus.circle", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabitem.cart`.
    var tabitemCart: RswiftResources.ImageResource { .init(name: "tabitem.cart", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabitem.home`.
    var tabitemHome: RswiftResources.ImageResource { .init(name: "tabitem.home", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabitem.home.mymenu`.
    var tabitemHomeMymenu: RswiftResources.ImageResource { .init(name: "tabitem.home.mymenu", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tabitem.order`.
    var tabitemOrder: RswiftResources.ImageResource { .init(name: "tabitem.order", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tumbler`.
    var tumbler: RswiftResources.ImageResource { .init(name: "tumbler", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `xmark`.
    var xmark: RswiftResources.ImageResource { .init(name: "xmark", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `bean_loading.json`.
    var bean_loadingJson: RswiftResources.FileResource { .init(name: "bean_loading", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }
}